### ISSUE TITLE
ASP.NET Core Support 

### ISSUE THREAD

**Issue by NRohrer** [51Degrees/dotNET-Device-Detection#10]
Using code like `Request.Browser["IsMobile"]` no longer seems to be acceptable because [HttpBrowserCapabilities](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpbrowsercapabilities?view=netframework-4.7.2) class is no longer a thing in ASP.NET Core. 

Is there a way to still use your properties server side? Maybe with User-Agent strings? Is there a specific syntax required for that?

**Comment by JoshGrew51D** [comment]
Although it is not possible to use the Web Provider you can still create a DataSet and Provider using the core functionality. You can pass it a User-Agent string and it will return the match object.

If you haven't already, take a look at the usage examples [here](https://github.com/51Degrees/dotNET-Device-Detection/blob/master/Examples/Getting%20Started/Program.cs).

If you are installing the packages via NuGet you will want to just use 51degrees.mobi-core and 51degrees.mobi-data.

Any questions just let me know.

**Comment by NRohrer** [comment]
@JoshGrew51D I was able to get this working with your help. Thank you! Closing this issue.
