### ISSUE TITLE
Unit testing the Provider/DataSet/Match using Moq

### ISSUE THREAD

**Issue by seruminar** [51Degrees/dotNET-Device-Detection#15]
Hello, I have not been able to find information on how to mock the `Provider` or any of its descendant objects. Some of them have interfaces (`IMatch`) but those are incomplete. There is a `DataSetBuilder` but it doesn't appear to support a tiny inline dataset.

Is there a way we could at least have interfaces for mocking, or else make `DataSetBuilder` or `StreamFactory` support inline datasets? Or else, can you provide guidance on how to mock a `Provider` to allow test calls to `Match` and, from the match, calls to the indexer?

**Comment by Steve51D** [comment]
Hi @seruminar,

This repository contains the code for our version 3 API. This was designed without consideration for mocking, so doing so would involve writing your own wrapper around it.
Although we continue to publish new data files for v3 (and will continue to do so for as long as our customers need us to). We have no plans to make any more code changes for v3.

Our [version 4 API](https://github.com/51Degrees/device-detection-dotnet) was designed with mocking in mind and is easy to mock out-of-the-box.

**Comment by seruminar** [comment]
Okay, thank you! I'll work with my team to get a V4 license and update our API references.
