### ISSUE TITLE
New version of lite data

### ISSUE THREAD

**Issue by Misiu** [51Degrees/dotNET-Device-Detection#5]
I've noticed that last version of Your lite data file is from 4th December 2017.
It's mid March 2018.
Do You guys plan to release updated package?

**Comment by JoshGrew51D** [comment]
Hi There

We have recently committed some changes to our Java repository so you can download the Lite data file from [here](https://github.com/51Degrees/Java-Device-Detection/blob/master/data/51Degrees-LiteV3.2.dat).

We will be adding the data file to .NET once we have finished our next release.

**Comment by Misiu** [comment]
@JoshGrew51D thanks for link 👍 
It's always easier to update via Nuget, but replacing a single file is fine 😄

**Comment by Misiu** [comment]
@JoshGrew51D any news on that new release?
Where can I find latest version of Lite data?
https://github.com/51Degrees/Device-Detection/blob/master/data/51Degrees-LiteV3.2.dat?

Ideally there should be single data file for each client, this way I could just download it once a month.

P.S. any chance to get newest data file?
![51degrees_nextversion](https://user-images.githubusercontent.com/1741838/39912508-40b8835e-54ff-11e8-8288-6a8b569cb1e2.png)

**Comment by JoshGrew51D** [comment]
Just a quick note to let you know we have updated the data file.

The way we currently release lite data files is different to the enhanced data files, which can be automatically updated. This is something we will be looking into changing going forward.

**Comment by Misiu** [comment]
@JoshGrew51D thank You for the update. It would be awesome if both enhanced and lite would share the same update mechanism. Hopefully, this will be added at some point 👍
