### ISSUE TITLE
Strong-named NET40 version prevents multi-targeting

### ISSUE THREAD

**Issue by onyxmaster** [51Degrees/dotNET-Device-Detection#6]
Consider the following example:
The project `A` that has a target framework `netstandard2.0` has a package reference to `51degrees.mobi-core`. The project `B` targets the `net471` framework, but reference project `A`. This is usually not a problem, since the build system will use the `net471` version for project B and substitute the library as needed.
Unfortunately, your nuget package has strongly named `NET40` version and a non-strongly named `netstandard1.6` version. This leads to the assembly for class library `A` containing a reference to `FiftyOne.Foundation.dll` with `PublicKeyToken=null` (which is OK), but the project `B` references the one with `PublicKeyToken=e0b3a8da0bbce49c`.
This prevents loading of class library `A` when project `B` is launched.

P.S. Our customer order numbers are WEB6290 and WEB10209.

**Comment by JoshGrew51D** [comment]
For the older assembly targeting .NET framework, both Signtool and Strongly named are done but it looks like for the .NET standard assembly, only the Signtool step is done.

We will look into the release process to correct this.

Can you confirm if you require an updated NuGet package to correct this or are we able to provide the strongly-named dll?

**Comment by onyxmaster** [comment]
Thank you for responding.
The NuGet package is required, because we install it with project PackageReferences.

**Comment by JoshGrew51D** [comment]
Just a quick update to let you know we are looking to include these changes in the release at the end of this month.

**Comment by onyxmaster** [comment]
Thank you for the heads-up, looking forward to the new release.

**Comment by JoshGrew51D** [comment]
The updated NuGet packages are now available. Please take a look and let me know how you get on.

**Comment by onyxmaster** [comment]
Thank you, Josh, I'm going to check on it this week.

**Comment by onyxmaster** [comment]
It works, thank you!
