### ISSUE TITLE
Trie support for .Net

### ISSUE THREAD

**Issue by nabeelbukhari** [51Degrees/dotNET-Device-Detection#7]
Hi Guys,

I want to use Trie based device detection in .Net. It's also mentioned in your documentation but cannot use it as its not available in API.

Can you please help with it?

Thanks
Nabeel

**Comment by Joseph51D** [comment]
Hi @nabeelbukhari 

Thanks for your query. Trie in Native .NET has been deprecated for performance reasons, we now provide a much faster Hash algorithm in C using a .NET wrapper.

Please see the solution in https://github.com/51Degrees/Device-Detection/tree/master/VisualStudio for examples.

Regards,
Joe

**Comment by nabeelbukhari** [comment]
I checked out the code but everytime I run the examples, it complains about file. Secondly, when are you going to release it as Nuget package?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Joseph51D** [comment]
Can you provide more details on the file it complains about? If it's the 'trie' file then that is now distributed via the 51Degrees website. A free subscription to download the file can be obtained at https://51degrees.com/products/store.

I will get back to you on packaging.

Joe

**Comment by nabeelbukhari** [comment]
Nevermind, it was path issue. I am able to run it. Please update on when we can get it as part of nuget package.

**Comment by Joseph51D** [comment]
Hi @nabeelbukhari 

To discuss packaging, please email us at support@51degrees.com

Regards,
Joe

**Comment by JoshGrew51D** [comment]
Closing this issue as it has moved to our internal support. Any issues please let us know.
