### ISSUE TITLE
new datafile corrupt

### ISSUE THREAD

**Issue by rkajbaf** [51Degrees/dotNET-Device-Detection#8]
It would appear the latest version of  the data files are conflicted pointer files instead of actual data.

Here is the contents of the 3.2 dat file

version https://git-lfs.github.com/spec/v1
<<<<<<< HEAD
oid sha256:455abb0f261c80c84aa8d782604f11ecf978fbef1b3a5e34ab469759be6b4305
size 115333455
=======
oid sha256:bd26c4c81cee8cb07335a694bf15a558a1565de8ca062a1a537d8e6f44ab5d32
size 126072666
>>>>>>> 85c773f3ef602f9c3507c77372583d25b5cd0529

**Comment by Joseph51D** [comment]
Hi @rkajbaf 

Thanks for alerting us. We've pushed a hot-fix to resolve this.

Regards,
Joe
